#!/usr/bin/env python3
#!/usr/bin/env python3

import csv
import sys
import random

def bubble_sort(arr):
    n = len(arr)

    # Traverse through all array elements
    for i in range(n):
        # Last i elements are already in place, so we don't need to check them
        for j in range(0, n-i-1):
            # Swap if the element found is greater than the next element
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]

    # Return the sorted list
    return arr

if __name__ == "__main__":

    if len(sys.argv) != 2:
        print("Usage: {} inputfile".format(sys.argv[0]))
        sys.exit(1)

    input_filename = sys.argv[1]

    with open(input_filename, 'r') as csvfile:
        csvreader = csv.reader(csvfile)
        input_list = [row for row in csvreader]

    bubble_sort(input_list)

    for row in input_list:
        print(','.join(row))